Dynamic vocal channel
la-zad/Zadier pull request #4
Opened 2024-02-17 19:28 UTC by glcraft

When you connect to a Channel factory (which has send message permission disabled), you are moved to a temporary channel

2024-02-17 19:46 UTC, Arthur-Devs approved these changes, later dismissed

2024-02-19 18:11 UTC, vic1707 commented on src/events/dyn_vocal/on_disconnect.ts
> + * @permission  - idk
```suggestion
 * @permission  - None
```

2024-02-19 18:20 UTC, vic1707 commented on src/events/dyn_vocal/on_disconnect.ts
> +        }
```suggestion
    async execute({ channel }, _) {
        if (!channel || !channel.name.startsWith('Nouveau') || channel.members.size) return;

        await channel.delete();
    },
```

2024-02-19 18:20 UTC, vic1707 commented on src/events/dyn_vocal/on_connect.ts
> +        await member.voice.setChannel(chan);
```suggestion
    async execute(_, { guild, channel, member }) {
        if (!channel || channel.name.startsWith('Nouveau') || !member) return;

        const chan = await guild.channels.create({
            type: ChannelType.GuildVoice,
            name: `${member.nickname ?? member.user.username} qui parle`,
            parent: channel.parent,
            position: channel.position,
        });

        await member.voice.setChannel(chan);
```

2024-02-19 18:21 UTC, vic1707 approved these changes, later dismissed

2024-02-20 19:51 UTC, vic1707 requested changes

2024-02-20 19:51 UTC, vic1707 commented on src/events/dyn_vocal/on_disconnect.ts
> +/*
```suggestion
/**
```

2024-02-20 19:51 UTC, vic1707 commented on src/events/dyn_vocal/on_connect.ts
> +/*
```suggestion
/**
```

2024-02-20 22:13 UTC, vic1707 approved these changes

2024-02-20 22:27 UTC, merged